# Generated by Django 2.0.6 on 2018-09-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cedula_Admin', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('Direccion', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_elemento', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('Facultad', models.CharField(max_length=100)),
                ('Departamento', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('id_cedula_Admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cedula_Estu', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('Direccion', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cedula_Profe', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('asignatura', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Sala', models.IntegerField()),
                ('salon', models.IntegerField()),
                ('Facultad', models.CharField(max_length=100)),
                ('Departamento', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('id_cedula_Admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Administrador')),
            ],
        ),
    ]
