# Generated by Django 2.0.6 on 2018-09-10 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_elemento', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ip', models.IntegerField()),
                ('ip_numero', models.IntegerField()),
                ('mascara', models.IntegerField()),
                ('asignacion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_informe', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('id_pre_disp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Dispositivo')),
                ('id_pre_ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Ip')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_role', models.IntegerField()),
                ('roles', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cedula', models.IntegerField()),
                ('nombreapellido', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Roles')),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.RenameField(
            model_name='elemento',
            old_name='Departamento',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='elemento',
            old_name='Facultad',
            new_name='encargado',
        ),
        migrations.RenameField(
            model_name='elemento',
            old_name='nombre',
            new_name='facultad',
        ),
        migrations.RemoveField(
            model_name='elemento',
            name='id_cedula_Admin',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='Departamento',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='Facultad',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='id_cedula_Admin',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='salon',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='status',
        ),
        migrations.AddField(
            model_name='sala',
            name='datos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Elemento'),
        ),
        migrations.AddField(
            model_name='sala',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='piso',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='id_pre_sala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Sala'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='id_pre_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Usuario'),
        ),
        migrations.AddField(
            model_name='ip',
            name='datos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Elemento'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='datos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Elemento'),
        ),
    ]
