# Generated by Django 2.0.6 on 2018-09-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180909_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='datos',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='datos',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='departamento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='encargado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='facultad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='departamento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='encargado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='facultad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='departamento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='encargado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='facultad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
