# Generated by Django 2.0.6 on 2018-09-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180910_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='datos',
        ),
    ]
