# Generated by Django 2.0.6 on 2018-09-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_dispositivo_datos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='departamento',
        ),
    ]
